apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
      - name: node-app
        imagePullPolicy: IfNotPresent  # Atualizado para buscar do ECR
        image: <aws-account-id>.dkr.ecr.<regiao>.amazonaws.com/order-system-app:latest
        ports:
        - containerPort: 3000
        env:
        - name: MONGO_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: username
        - name: MONGO_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: password
        - name: MONGO_HOST
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: host
        - name: MONGO_PORT
          value: "27017"
        - name: MONGO_DATABASE
          value: "order_system"
        resources:
          limits:
            memory: "32Mi"
            cpu: "100m"
          requests:
            memory: "16Mi"
            cpu: "50m"