apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
      - name: node-app
        imagePullPolicy: IfNotPresent  # Atualizado para usar a última imagem disponível se não estiver em cache
        image: 740588470221.dkr.ecr.us-east-1.amazonaws.com/order-system-app:latest  # Endereço da imagem diretamente inserido
        ports:
        - containerPort: 3000
        env:
        - name: DB_MASTER_USERNAME
          value: "${{ secrets.DB_MASTER_USERNAME }}"
        - name: DB_MASTER_PASSWORD
          value: "${{ secrets.DB_MASTER_PASSWORD }}"
        - name: DB_URI
          value: "${{ secrets.DB_URI }}"
        resources:
          limits:
            memory: "64Mi"
            cpu: "250m"
          requests:
            memory: "32Mi"
            cpu: "125m"