name: Deploy Order System App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # Substituir os placeholders do Kubernetes manifest
    - name: Replace placeholders in Kubernetes manifest
      run: |
        sed -i 's/<aws-account-id>/${{ secrets.AWS_ACCOUNT_ID }}/g' ./order-system-app/k8s/appnode-deployment.yaml
        sed -i 's/<regiao>/${{ secrets.AWS_REGION }}/g' ./order-system-app/k8s/appnode-deployment.yaml

    # Configurar as credenciais da AWS
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    # Instalar kubectl
    - name: Install kubectl
      uses: azure/setup-kubectl@v1
      with:
        version: 'v1.22.0'

    # Atualizar o kubeconfig para conectar ao EKS
    - name: Update kubeconfig
      run: aws eks update-kubeconfig --region ${{ secrets.AWS_REGION }} --name my-eks-cluster

    # Fazer o deploy no Kubernetes
    - name: Deploy app to Kubernetes
      run: |
        kubectl apply -f ./order-system-app/k8s/appnode-deployment.yaml
        kubectl apply -f ./order-system-app/k8s/appnode-service.yaml

    # Verificar o status do Deployment
    - name: Verify Deployment
      run: kubectl rollout status deployment/node-app