name: Deploy Order System App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout do código
    - name: Checkout code
      uses: actions/checkout@v2

    # Configurar o Node.js
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    # Instalar dependências
    - name: Install dependencies
      run: npm install
      working-directory: ./order-system-app

    # Build e empacotamento do app (se necessário)
    - name: Build and package app
      run: npm run build
      working-directory: ./order-system-app

    # Listar arquivos YAML de deployment para garantir que eles estão acessíveis
    - name: List Kubernetes Infra Files
      run: ls -la ./k8s/

    # Aplicar o deployment e service do app no Kubernetes
    - name: Deploy app to Kubernetes
      run: |
        kubectl apply -f ./k8s/appnode-deployment.yaml
        kubectl apply -f ./k8s/appnode-service.yaml

    # Verificar o status do deployment
    - name: Verify Deployment
      run: kubectl rollout status deployment/node-app